# Generated by Django 4.2.14 on 2024-08-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susbstation', models.CharField(max_length=50)),
                ('dev_typ', models.CharField(max_length=50)),
                ('dev', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('MW', 'MW'), ('KV', 'KV'), ('Hz', 'Hz')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Values30min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.target')),
            ],
        ),
    ]
