# Generated by Django 4.2.14 on 2024-08-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('danger', models.CharField(choices=[('Casual', 'Casual'), ('Warning', 'Warning'), ('Alarming', 'Alarming'), ('Dangerous', 'Dangerous')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.target')),
            ],
        ),
    ]
