# Generated by Django 4.2.14 on 2024-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='danger',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Warning', 'Warning'), ('Dangerous', 'Dangerous')], max_length=10),
        ),
    ]
